version: '3'
services:

  backend:
    container_name: SoundGroup-Backend
    restart: unless-stopped
    image: sg-backend
    build: ./Backend/
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    volumes:
      - .:/code

  app:
    container_name: SoundGroup-Frontend
    restart: unless-stopped
    image: sg-frontend
    build: ./Frontend/
    ports:
      - "3000:3000"
    tty: true

  mongo:
    container_name: SoundGroup-MongoDB
    restart: unless-stopped
    image: mongo
    volumes:
      - mongodata:/usr/share/mongodb/data
    ports:
      - "27017:27017"

volumes:
  mongodata:
